"""Centralized constants for eagle-watcher"""

# HTTP Server ports
REMOTE_SERVER_PORT = 9800
PANEL_SERVER_PORT = 9801

# HUD Panel dimensions
PANEL_WIDTH = 420
PANEL_HEIGHT = 640
PANEL_MIN_WIDTH = 360
PANEL_MIN_HEIGHT = 400
PANEL_MAX_WIDTH = 800
PANEL_MAX_HEIGHT = 1200

# Timeouts (seconds)
EAGLE_API_DEFAULT_TIMEOUT = 30
EAGLE_API_FILE_TIMEOUT = 60
EAGLE_API_URL_TIMEOUT = 120
EAGLE_API_PING_TIMEOUT = 5

# Cache
STATUS_CACHE_TTL = 10
AI_CACHE_MAX_AGE_DAYS = 30

# File processing
MAX_PROCESSED_FILES = 1000
TRIM_KEEP_COUNT = 500
WATCH_POLL_INTERVAL = 2.0
LARGE_FILE_THRESHOLD = 10 * 1024 * 1024

# Retry
MAX_RETRIES = 3
RETRY_DELAY = 2
RETRY_QUEUE_MAXLEN = 100

# Knowledge
DEFAULT_CONFIDENCE_NEW = 0.7
CONFIDENCE_PER_MATCH = 0.15
MAX_CONFIDENCE = 0.98
KNOWLEDGE_AUTO_CLEANUP_THRESHOLD = 500

# History
MAX_HISTORY_ENTRIES = 2000